### ISSUE TITLE
Infrastructure as Code

### ISSUE THREAD

**Issue by bdevic** [juggr/Planung#17]
Infrastructure as Code is one of the important cornerstones of continuous delivery. The concept that infrastructure should be treated as code is really powerful. Server configuration, services, installed packages, relationships with other servers etc...should be modeled as code to be automated and have a predictable outcome, removing manual steps prone to errors and decreasing the cycle time. 

Spinning up a new virtual environment or a new version of the environment then becomes a matter of executing a script that can create and provision an image or set of images – from the barebone operating system to the complete application stack installed and configured. 

This concept is increasingly important today when the number of environments and their instances has gone up by orders of magnitudes and the release frequency has moved from monthly to weekly or even daily releases. 

In this session we will showcase a few popular tools used to implement this concept: `Vagrant`, `Puppet` and `Docker`.

**Comment by manuel-mauky** [comment]
Thanks for the submission :-)

At the last user group meeting you set that you could give the task for this topic at the next user group meeting (29. october). Is this still valid? When you confirm this I will update the web page and the Google+ page.

regards

**Comment by manuel-mauky** [comment]
Before I forget: Of cause you can give the talk in english if this is easier for you. I think every attendee will understand english anyway.

**Comment by bdevic** [comment]
It is still valid, please update the web page with the meeting information. Yes, english will probably be easier for you to listen to :)
