### ISSUE TITLE
Hazelcast - Synchronization von In-Memory-Daten

### ISSUE THREAD

**Issue by SteffenSeidler** [juggr/Planung#6]
Hazelcast ist ein vielseitiges Framework zur einfachen Synchronization von Daten, die sich In-Memory innerhalb einer Applikation befinden. Damit ist es für Anwendungen gedacht, bei denen eine Synchronization durch eine "externe" Technologie wie Datenbanken zu einem erheblichen Performanceverlust führt.

Durch die Verteilung der Daten auf mehrere Knoten ist es ein gutes Mittel zur horizontalen Skalierbarkeit bei Synchronität der Daten innerhalb des Clusters. Zusätzlich lässt sich die Verfügbarkeit/Ausfallsicherheit durch die Hinzunahme weiterer (Backup-)Knoten steigern.

**Comment by SteffenSeidler** [comment]
Vortragender: Steffen Seidler
am: 28.05.2014 19:00
Ort: DSER, Steinstr. 11

**Comment by manuel-mauky** [comment]
Vielen Dank für das Vortragsangebot. Ich werde am Wochenende dann gleich die Webseite updaten und würde deinen Text als Ankündigung benutzen.
Ich freu mich schon auf das Thema. :-)
