### ISSUE TITLE
MoSKito - ein Monitoring Framework

### ISSUE THREAD

**Issue by SteffenSeidler** [juggr/Planung#9]
Ein Framework zum Health-and-Performance-Monitoring. Mittels AOP-Technik wird es in die Anwendung integriert und liefert zahlreiche Einblicke in die Nutzung einer Applikation und hilft bei der Identifizierung von Bottlenecks und Performancebremsen.

**Comment by SteffenSeidler** [comment]
Inzwischen habe ich mich mal mehr mit MoSKito auseinandergesetzt, daher wird der Vortrag am 28.01.2015 darüber gehen.

Hier eine etwas ausführlicherer Text für die Startseite:
Es wird immer wichtiger WebAnwendungen überwachen zu können, um Probleme frühzeitig zu erkennen und Gegenmaßnahmen einleiten zu können. Hierfür wurde MoSKito geschaffen. Ursprünglich wurde es für Parship entwickelt, aber inzwischen ist es in ein eigenständiges Projekt auf GitHub ausgegliedert und steht nun allen Interessierten zur Verfügung.

In dem Vortrag werden wir die einzelnen Komponenten der MoSKito-Toolbox anhand einer simplen Beispiel-Anwendung vorstellen. Dazu zählen die Datenerhebung für das Monitoring technischer Auffälligkeiten, die Visualisierung über eine integriertes oder standalone WebUI, zentrale Persistierung zur späteren Auswertung, sowie ein Kontrollzentrum, welches durchaus auch als Wall-Monitor eignet.

Desweiteren werden wir die einfache Integration, sowie Möglichkeiten zur Erweiterung näher beleuchten. Denn in MoSKito kann man nicht nur Informationen technischer Natur sammeln, die für Entwickler relevant sind (Verarbeitungszeiten, Systemlast, etc.), sondern auch Daten mit Businessvalue (Verkaufszahlen, etc.). So kann MoSKito auch für Management und Marketing interessant sein.

**Comment by manuel-mauky** [comment]
Sehr gut. Ich hab die News hinzugefügt: http://www.jug-gr.de/2015/01/28/moskito.html
Google+ Meldung folgt.
